test:
  stripe_publishable_key: value
  stripe_secret_key: value
  google_api_key: value
  email_user_name: value
  email_password: value

development:
  stripe_publishable_key: value
  stripe_secret_key: value
  google_api_key: value
  email_user_name: value
  email_password: value

production:
  stripe_publishable_key: value
  stripe_secret_key: value
  google_api_key: value
  email_user_name: value
  email_password: value

secret_key_base: value